[versions]
kotlin = "1.6.10"
ksp = "1.6.10-1.0.4"
spring-boot = "2.6.6"
spring-dependencyManagement = "1.0.11.RELEASE"
spring-cloud = "3.1.1"
gradle-docker = "0.32.0"
gradle-lombok = "6.4.1"
gradle-gitProperties = "2.4.0"
kotlinx-json = "1.3.2"
kotlinx-coroutines = "1.6.0"
discord4j = "3.3.0-SNAPSHOT"
reactor-kotlin = "1.1.6"
jgit = "6.1.0.202203080745-r"
java-curl = "1.2.2.2"
java-ffmpeg = "0.6.2"
jraw = "1.2.0"
om-dsl = "1.3.1"
querydsl = "5.0.0"
trove4j = "3.0.3"
springmockk = "3.1.1"
strikt = "0.34.1"
kotlinPoet = "1.10.2"
kotlinBard = "0.4.1"
kaseChange = "1.3.0"
kotlinCompileTesting = "1.4.7"
junit = "5.8.2"
springdoc = "1.6.6"
gradle-node = "3.2.1"
guava = "31.1-jre"
nokee = "0.5.0-930919a0"
opencsv = "5.6"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-plugin-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
nokee-jni = { id = "dev.nokee.jni-library", version.ref = "nokee" }
nokee-c-language = { id = "dev.nokee.c-language", version.ref = "nokee" }
nokee-c-library = { id = "dev.nokee.c-library", version.ref = "nokee" }

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-dependencyManagement" }
gradle-docker = { id = "com.palantir.docker", version.ref = "gradle-docker" }
gradle-lombok = { id = "io.freefair.lombok", version.ref = "gradle-lombok" }
gradle-gitProperties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gradle-gitProperties" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gradle-node = { id = "com.github.node-gradle.node", version.ref = "gradle-node" }

[libraries]
kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-scriptingCompiler = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
mysqlConnector = { module = "mysql:mysql-connector-java" }
spring-cloud = { module = "org.springframework.cloud:spring-cloud-starter", version.ref = "spring-cloud" }
discord4j = { module = "com.discord4j:discord4j-core", version.ref = "discord4j" }
reactor-kotlin = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions", version.ref = "reactor-kotlin" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
java-curl = { module = "com.github.rockswang:java-curl", version.ref = "java-curl" }
jraw = { module = "com.faendir.jraw:JRAW", version.ref = "jraw" }
java-ffmpeg = { module = "net.bramp.ffmpeg:ffmpeg", version.ref = "java-ffmpeg" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
om-dsl = { module = "com.faendir.om:dsl", version.ref = "om-dsl" }
querydsl-jpa = { module = "com.querydsl:querydsl-jpa", version.ref = "querydsl" }
querydsl-core = { module = "com.querydsl:querydsl-core", version.ref = "querydsl" }
querydsl-apt = { module = "com.querydsl:querydsl-apt", version.ref = "querydsl" }
querydsl-kotlinCodegen = { module = "com.querydsl:querydsl-kotlin-codegen", version.ref = "querydsl" }
spring-boot-configurationProcessor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test" }
trove4j = { module = "net.sf.trove4j:trove4j", version.ref = "trove4j" }
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }
strikt = { module = "io.strikt:strikt-core", version.ref = "strikt" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlinBard = { module = "com.faendir:kotlinbard", version.ref = "kotlinBard" }
kotlinCompileTesting = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "kotlinCompileTesting" }
kaseChange = { module = "net.pearx.kasechange:kasechange-jvm", version.ref = "kaseChange" }
junit = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
springdoc = { module = "org.springdoc:springdoc-openapi-ui", version.ref = "springdoc" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
spring-core = { module = "org.springframework:spring-core" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }

